n26Bono/force-app/main/default/objects/Product_Table__c/Product_Table__c.object-meta.xml
<CustomObject>
    <label>Product Table</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Product Table Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

n26Bono/force-app/main/default/objects/Product_Table__c/fields/ATM_Fee_in_Other_Currency__c.field-meta.xml
<CustomField>
    <fullName>ATM_Fee_in_Other_Currency__c</fullName>
    <description>Created by BMONDAL on 13th November 2022 for the purpose of showing ATM Fee details in all currencies available.</description>
    <label>ATM Fee in Other Currency</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

n26Bono/force-app/main/default/objects/Product_Table__c/fields/Card_Replacement_Cost__c.field-meta.xml
<CustomField>
    <fullName>Card_Replacement_Cost__c</fullName>
    <description>Created by BMONDAL on 13th November 2022 for the purpose of showing Card Replacement Cost per standard product available.</description>
    <label>Card Replacement Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

n26Bono/force-app/main/default/objects/Product_Table__c/fields/Cost_Per_Calendar_Month__c.field-meta.xml
<CustomField>
    <fullName>Cost_Per_Calendar_Month__c</fullName>
    <description>Created by BMONDAL on 13th November 2022 for the purpose of showing Cost Per Calendar Month details for the plans</description>
    <label>Cost Per Calendar Month</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

n26Bono/force-app/main/default/objects/Product_Table__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Created by BMONDAL on 13th November 2022. Country details.</description>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

n26Bono/force-app/main/default/objects/Product_Table__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <description>Created by BMONDAL on 13th November 2022. To enlist products available.</description>
    <label>Product Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Name</valueSetName>
    </valueSet>
</CustomField>

n26Bono/force-app/main/default/globalValueSets/Product_Name.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
    </customValue>
    <customValue>
        <fullName>Black</fullName>
    </customValue>
    <customValue>
        <fullName>Metal</fullName>
    </customValue>
    <masterLabel>Product Name</masterLabel>
</GlobalValueSet>

n26Bono/force-app/main/default/classes/CustomerProductWrapper.cls
/*
* Name            :    CustomerProductWrapper
* Description     :    This is the wrapper class for custommer product information
* Created Date    :    [14th Nov , 2022]
* Created By      :    [Bonoshree Mondal]
*
* Date Modified        Modified By             Description of the update
   14th-Nov-2022     Bonoshree Mondal          Created
*/
public class CustomerProductWrapper {

    @AuraEnabled
    public Decimal Cost_per_calender_month ;

    @AuraEnabled
    public Decimal ATM_fee_in_other_currency ;
    
	@AuraEnabled
    public Decimal Card_replacement_cost { get;set; }
    
    @AuraEnabled
    public string productName;
    
    @AuraEnabled
    public string country;
    
    @AuraEnabled
    public string currencyType;
    
    public CustomerProductWrapper(Product_Table__c pt, Id conId){
        this.productName = pt.Product_Name__c;
        this.country = pt.Country__c;
        this.currencyType = pt.CurrencyIsoCode;
        this.Cost_per_calender_month = pt.Cost_Per_Calendar_Month__c;
        this.ATM_fee_in_other_currency = pt.ATM_Fee_in_Other_Currency__c;
        this.Card_replacement_cost = pt.Card_Replacement_Cost__c;
        this.discount();
    }
    private void discount(){
        // discount logic based on period of subscription or other factors
    }

    
}