n26Bono/force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <description>Created by BMONDAL on 13th November 2022. This field will help to store country of the customer.</description>
    <label>Home Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

n26Bono/force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>Created by BMONDAL on 13th November 2022. This field helps to store product details</description>
    <label>Product</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Name</valueSetName>
    </valueSet>
</CustomField>

n26Bono/force-app/main/default/objects/Product_Table__c/Product_Table__c.object-meta.xml
<CustomObject>
    <label>Product Table</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Product Table Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

n26Bono/force-app/main/default/objects/Product_Table__c/fields/ATM_Fee_in_Other_Currency__c.field-meta.xml
<CustomField>
    <fullName>ATM_Fee_in_Other_Currency__c</fullName>
    <description>Created by BMONDAL on 13th November 2022 for the purpose of showing ATM Fee details in all currencies available.</description>
    <label>ATM Fee in Other Currency</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

n26Bono/force-app/main/default/objects/Product_Table__c/fields/Card_Replacement_Cost__c.field-meta.xml
<CustomField>
    <fullName>Card_Replacement_Cost__c</fullName>
    <description>Created by BMONDAL on 13th November 2022 for the purpose of showing Card Replacement Cost per standard product available.</description>
    <label>Card Replacement Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

n26Bono/force-app/main/default/objects/Product_Table__c/fields/Cost_Per_Calendar_Month__c.field-meta.xml
<CustomField>
    <fullName>Cost_Per_Calendar_Month__c</fullName>
    <description>Created by BMONDAL on 13th November 2022 for the purpose of showing Cost Per Calendar Month details for the plans</description>
    <label>Cost Per Calendar Month</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

n26Bono/force-app/main/default/objects/Product_Table__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Created by BMONDAL on 13th November 2022. Country details.</description>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

n26Bono/force-app/main/default/objects/Product_Table__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <description>Created by BMONDAL on 13th November 2022. To enlist products available.</description>
    <label>Product Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Name</valueSetName>
    </valueSet>
</CustomField>

n26Bono/force-app/main/default/globalValueSets/Product_Name.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
    </customValue>
    <customValue>
        <fullName>Black</fullName>
    </customValue>
    <customValue>
        <fullName>Metal</fullName>
    </customValue>
    <masterLabel>Product Name</masterLabel>
</GlobalValueSet>

n26Bono/force-app/main/default/classes/CustomerDetailsForExternalSystem.cls
/*
* Name            :    CustomerDetailsForExternalSystem
* Description     :    This is the Restresource apex class for external system to get the customer prod information by their UUID
* Created Date    :    [14th Nov , 2022]
* Created By      :    [Bonoshree Mondal]
*
* Date Modified        Modified By             Description of the update
   14th-Nov-2022     Bonoshree Mondal          Created
*/
@RestResource(urlMapping='/getCustomerDetails/*')
global class CustomerDetailsForExternalSystem {
    
    @HttpGet
    global static CustomerDetailsForExternalSystem.ResponseWrapper getCustomerDetails() {
        ResponseWrapper response = new ResponseWrapper();
        try{
            RestRequest request = RestContext.request;
            // grab the UUID from the end of the URL
            String UUID = request.requestURI.substring(
            request.requestURI.lastIndexOf('/')+1);
            Contact con = [select id, product__c, Home_Country__c from Contact where UUID__c =: UUID];
            Product_Table__c pt = [select id, Country__c, Product_Name__c,Cost_Per_Calendar_Month__c, CurrencyIsoCode, Card_Replacement_Cost__c, ATM_Fee_in_Other_Currency__c from Product_Table__c where Product_Name__c =: con.product__c and Country__c =: con.Home_Country__c];
            response.cpw = new CustomerProductWrapper(pt, con.Id);
        }
        catch (Exception ex) {
            system.debug(ex.getMessage());
            response.errorMessage = ex.getMessage();
        }
        
        return response;
    }
    
    global class ResponseWrapper {

    @AuraEnabled
    public CustomerProductWrapper cpw ;

    @AuraEnabled
    public String errorMessage ;
    	    
    }
    
    
}