n26Bono/force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <description>Created by BMONDAL on 13th November 2022. This field will help to store country of the customer.</description>
    <label>Home Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

n26Bono/force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>Created by BMONDAL on 13th November 2022. This field helps to store product details</description>
    <label>Product</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Name</valueSetName>
    </valueSet>
</CustomField>

n26Bono/force-app/main/default/objects/Product_Table__c/Product_Table__c.object-meta.xml
<CustomObject>
    <label>Product Table</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Product Table Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

n26Bono/force-app/main/default/objects/Product_Table__c/fields/ATM_Fee_in_Other_Currency__c.field-meta.xml
<CustomField>
    <fullName>ATM_Fee_in_Other_Currency__c</fullName>
    <description>Created by BMONDAL on 13th November 2022 for the purpose of showing ATM Fee details in all currencies available.</description>
    <label>ATM Fee in Other Currency</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

n26Bono/force-app/main/default/objects/Product_Table__c/fields/Card_Replacement_Cost__c.field-meta.xml
<CustomField>
    <fullName>Card_Replacement_Cost__c</fullName>
    <description>Created by BMONDAL on 13th November 2022 for the purpose of showing Card Replacement Cost per standard product available.</description>
    <label>Card Replacement Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

n26Bono/force-app/main/default/objects/Product_Table__c/fields/Cost_Per_Calendar_Month__c.field-meta.xml
<CustomField>
    <fullName>Cost_Per_Calendar_Month__c</fullName>
    <description>Created by BMONDAL on 13th November 2022 for the purpose of showing Cost Per Calendar Month details for the plans</description>
    <label>Cost Per Calendar Month</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

n26Bono/force-app/main/default/objects/Product_Table__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Created by BMONDAL on 13th November 2022. Country details.</description>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

n26Bono/force-app/main/default/objects/Product_Table__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <description>Created by BMONDAL on 13th November 2022. To enlist products available.</description>
    <label>Product Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Name</valueSetName>
    </valueSet>
</CustomField>

n26Bono/force-app/main/default/globalValueSets/Product_Name.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
    </customValue>
    <customValue>
        <fullName>Black</fullName>
    </customValue>
    <customValue>
        <fullName>Metal</fullName>
    </customValue>
    <masterLabel>Product Name</masterLabel>
</GlobalValueSet>

n26Bono/force-app/main/default/classes/TestUtility.cls
/*
* Name            :    TestUtility
* Description     :    This is the Utility method for the test class for test data creation.
* Created Date    :    [14th Nov , 2022]
* Created By      :    [Bonoshree Mondal]
*
* Date Modified        Modified By             Description of the update
   14th-Nov-2022     Bonoshree Mondal          Created
*/
public class TestUtility {
    public static Account createAccount(Boolean isInsert) {
        Account account = new Account(Name = 'Test Account');

        if(isInsert) {
          insert account;
        }
        system.assert(true);

        return account;
    }
    
    public static Contact createContact(Boolean isInsert) {
        Account account = TestUtility.createAccount(true);
        Contact cont = new Contact();
        cont.FirstName='Test';
        cont.LastName='Test';
        cont.Accountid= account.id;
        cont.UUID__c = '1234';
        cont.Product__c = 'Standard';
        cont.Home_Country__c = 'ES';

        if(isInsert) {
          insert cont;
        }
        system.assert(true);

        return cont;
    }
    
    public static Case createCase(Boolean isInsert) {
        Contact con = TestUtility.createContact(true);
        Case c = new Case();
        c.contactId = con.Id;
        if(isInsert) {
          insert c;
        }
        system.assert(true);

        return c;
    }
    
    public static Product_Table__c createProdTable(Boolean isInsert) {
        Product_Table__c pt = new Product_Table__c();
        pt.Product_Name__c = 'Standard';
        pt.Cost_Per_Calendar_Month__c = 0;
        pt.ATM_Fee_in_Other_Currency__c = 1.70;
        pt.Card_Replacement_Cost__c = 6;
        pt.Country__c = 'ES';

        if(isInsert) {
          insert pt;
        }
        system.assert(true);

        return pt;
    }
    
    
}